### ISSUE TITLE
[BUG] Coroutines cannot be created as IL.

### ISSUE THREAD

**Issue by EliteMasterEric** [SamboyCoding/AudicaShredder#32] opened 2021-08-10 03:59 UTC
Application version: `2021.3.4`
Target application: `Gems of War (32-bit)`

Displayed error:
```
Generated IL:
    Action of type Cpp2IL.Core.Analysis.Actions.Important.CallManagedFunctionAction at (0x102645C2) is corrupt (Don't know what method is being called) and cannot be created as IL. Aborting here.
```

Part of the generated pseudocode includes:

```
    [instruction error - managed method being called is null]
    return
    throw new System.NullReferenceException()
```

This error appears when attempting to reverse a function which calls `MonoBehavior.StartCoroutine`. See [Unity's documentation on Coroutines](https://docs.unity3d.com/Manual/Coroutines.html), which follow an abnormal execution flow, utilizing `yield` calls to pause execution, resuming execution during the next frame of the game loop. These types of functions are tricky for .NET decompilation too, (ILSpy and dnSpy can reverse them now but weren't able to a couple of years ago).

Please let me know if anything else would be helpful in resolving this issue (such as the full method dump file, or the log output from the reversing process). Your hard work and excellent understanding of reverse engineering is greatly appreciated.

As an aside, the application I am reversing is a unique case in which very similar versions of the application binaries exist just before and just after the switch to IL2CPP.

**Comment by SamboyCoding** [comment] 2021-08-10 12:11
This is probably a case of something previous missing such that cpp2il can't work out what the instance for that method is, while there are multiple methods at the same address there. 

I'm familiar with how coroutines work, and it's actually even more complicated than you say - there is no such thing as a "yield" instruction in the underlying IL code, instead the c# compiler creates an anonymous IEnumerator class which does the logic on each call to MoveNext. But an actual call to StartCoroutine shouldn't error, but it won't show anything useful at all.

Also, on average, 50-60% of a game cannot be created as IL, so coroutines aren't a particularly novel case. 

That said, I do actually have Gems of War in my steam library, so if you can tell me which function this is, I'll take a look and try and fix this one case for you, if the method is of particular interest.

**Comment by EliteMasterEric** [comment] 2021-08-10 16:58
Hey, thanks for taking the time to write up your response.

The particular case I chose was not because of any particular interest. One of the main functions I'm interested in (`PuzzleSpell#DelayCallDoSpellSteps`) is a massive and complicated function that handles a lot of things, and is about 3,000 lines long, and is a heaping spaghetti pile of `goto` calls (yes, in C#), but Cpp2IL outputs almost nothing. I instead looked at a smaller function (`MedalEquipMenu#SaveAndCloseMenu`), which has the following benefits:

* The function is much smaller and thus easier to evaluate, while still utilizing coroutines and thus containing a mostly blank Generated Pseudocode body.
* The function experiences a similar issue to the one above, where almost all of the function is left blank.
* The function, unless the developers did some modification to fix a bug or something, should be very similar or almost identical as its state just before the binary conversion to IL2CPP. DelayCallDoSpellSteps probably changes every update at least somewhat.

Doing some evaluation on the actual game would be greatly appreciated, not just from me but the other members of the Gems of War community who have been continuing to utilize reverse engineering to create things like player profile viewers and PvP leaderboard archives, and additionally from other users who interact with games that heavily utilize coroutines. 😄 

As mentioned, an earlier version of the game exists which ILSpy can trivially decompile to allow you to see the exact corresponding code, at least for some functions. [DepotDownloader](https://github.com/SteamRE/DepotDownloader) can fetch [the files from version 5.1.0](https://steamdb.info/depot/329111/history/?changeid=M:4164265782433069508).

**Comment by SamboyCoding** [comment] 2021-08-10 17:00
Thanks, I'll take a look when I can. Probably won't do the whole depotdownloader thing - I don't often need to refer to the original method for small ones like this MedalEquipMenu one.

**Comment by EliteMasterEric** [comment] 2021-09-19 01:07
@SamboyCoding, I don't want to bother you if you're busy, but I see several changes have been made to this repo recently, and I'm wondering if any progress has been made on this. Thank you for all the hard work, I understand open source development can be time consuming :)

**Comment by SamboyCoding** [comment] 2021-09-19 13:21
Hi @MasterEric I've been focused on arm stuff recently, so nothing has been done on this. That said, it's still on my radar.

**Comment by SamboyCoding** [comment] 2021-09-19 13:36
Just from a cursory glance, SaveAndCloseMenu is missing a call to an il2cpp helper function of some sort. I'm now trying to work out what it is.

**Comment by SamboyCoding** [comment] 2021-09-19 14:10
Okay, worked out the root cause and fixed it in https://github.com/SamboyCoding/Cpp2IL/commit/d94b6949ff91a45655017f2a693901cf8992f5cf. The method doesn't contain a lot, which is what I expected - it is indeed "mostly empty":
![image](https://user-images.githubusercontent.com/7011721/133930598-139076e0-c306-4111-a477-e0194a4cc062.png)

There's still a problem there with that Dispose call - it should actually be a constructor call - but that's a larger issue.

**Comment by SamboyCoding** [comment] 2021-10-05 03:16
Going to close this for now as the underlying problem (the api calls) has been fixed

**Closed as completed by SamboyCoding** 2021-10-05 03:16 UTC
Labels: bug
